language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.4.10

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django_nose
#  - pip install coveralls
  - pip install radon
  - pip install pep8
  - pip instal django_behave


# command to run tests
script: python manage.py test


after_success:
  - radon mi currencyapp/ , utils/
  - radon cc currencyapp/ , utils/
  - radon raw currencyapp/ , utils/
#  - coveralls
  - pep8 currencyapp/
  - pep8 utils/
